"""K-8 /init slash command (Phase 4 v0.20.0 borrow).

扫描 cwd (read README + pyproject.toml/package.json/setup.py + ls top-level) +
套用 minimal AGENTS.md 模板 (跟现有 69825 bytes 1:1 集成, additive 0 改).

跟 mavis 4 件套 1:1 配对 + CAND-084 8-03 22:10 lesson "估时前必 verify 引擎能力":
- 后端先调查再设计: 借 acp_adapter/server.py:1640 _handle_slash_command 现有 dispatch
  (handler dict pattern 1:1 配对 /context /help /model /tools /reset /compact /steer /queue /version).
  K-8 加 /init 是 1 file additive + 1 file edit 0 改旧
- Cherry-pick split bug class: 1 commit 0 split, _ADVERTISED_COMMANDS + handler dict + _cmd_init
  3 处 1:1 配对 (跟 /context 现有 1:1 配对). grep 旧名 0 命中
- UX 倒退审计: 现有 9 个 slash command (help/model/tools/context/reset/compact/steer/queue/version)
  不变. K-8 /init 是独立 add-only path. 现有 AGENTS.md 不覆盖 (init_agents_md force=False)
- 估时前必 verify 引擎能力: K-8 verify 后端 acp_adapter/server.py _ADVERTISED_COMMANDS +
  _handle_slash_command handler dict + _cmd_* 1:1 配对 pattern. AGENTS.md 现有 69825 bytes
  (完整 dev guide 模板) additive 0 改

跟 AIMC 4 铁律 1:1: 不反向调整 (0 改现有 9 slash command) / 不写回 upstream (0 push 跟 8-05
阶段批推 1:1) / 0 corrupt (1 file additive, 0 改旧 file) / fail-fast (跟 batch push + CI 1:1 配对)
"""

from __future__ import annotations

from pathlib import Path


# 模板跟 plan K-8 1:1 配对 (跟现有 AGENTS.md 69825 bytes spirit 1:1, additive 0 改)
AGENTS_MD_TEMPLATE = """# {project_name} - Development Guide

Auto-generated by hermes /init (K-8, Phase 4 v0.20.0 borrow).

## Project Description

{readme_excerpt}

## Project Metadata

{pyproject_excerpt}

## Structure (top-level, 最多 10 entries)

{structure}

## How this was generated

K-8 (Phase 4 /init slash command) reads README.md + pyproject.toml/package.json/setup.py +
ls cwd top-level (max 10 entries), 套用 minimal AGENTS.md 模板. additive 0 改 (现有
AGENTS.md 默认不覆盖, 需 force=True).

跟现有 69825 bytes AGENTS.md spirit 1:1 配对: 这是 minimal starter, 跑 /init 后 user 跟
agent 应手动扩展.
"""


def scan_cwd(cwd: Path) -> dict:
    """扫描 cwd 返回结构信息 (跟 plan K-8 §6 step 1:1 配对).

    Returns dict with:
    - project_name: cwd 顶层目录名
    - structure: list[str] (top-level entries, 0 hidden, max 10)
    - readme_excerpt: str (README.md 前 20 行, 0 README 返 "(no README.md found)")
    - pyproject_excerpt: str (pyproject.toml/package.json/setup.py 前 10 行, 0 返 "(not found)")
    """
    structure: list[str] = []
    readme_excerpt = "(no README.md found)"
    pyproject_excerpt = "(no pyproject.toml / package.json / setup.py found)"

    # ls top-level (限 10 entries, 0 hidden)
    try:
        for entry in sorted(cwd.iterdir())[:10]:
            if entry.name.startswith("."):
                continue
            structure.append(entry.name)
    except OSError:
        pass

    # read README.md (前 20 行)
    readme_path = cwd / "README.md"
    if readme_path.is_file():
        try:
            readme_lines = readme_path.read_text(
                encoding="utf-8", errors="replace"
            ).splitlines()[:20]
            readme_excerpt = "\n".join(readme_lines) or "(README.md is empty)"
        except OSError:
            pass

    # read pyproject.toml / package.json / setup.py (前 10 行, 优先 pyproject.toml)
    for name in ("pyproject.toml", "package.json", "setup.py"):
        p = cwd / name
        if p.is_file():
            try:
                lines = p.read_text(
                    encoding="utf-8", errors="replace"
                ).splitlines()[:10]
                pyproject_excerpt = f"# {name}\n" + "\n".join(lines)
                break  # 第一个匹配的优先级最高
            except OSError:
                pass

    return {
        "project_name": cwd.name or "(unnamed)",
        "structure": structure,
        "readme_excerpt": readme_excerpt,
        "pyproject_excerpt": pyproject_excerpt,
    }


def render_agents_md(cwd: Path) -> str:
    """生成 AGENTS.md 模板内容 (跟 plan K-8 §6 1:1 配对)."""
    info = scan_cwd(cwd)
    structure_str = (
        "\n".join(f"- {s}" for s in info["structure"]) or "(empty)"
    )
    return AGENTS_MD_TEMPLATE.format(
        project_name=info["project_name"],
        readme_excerpt=info["readme_excerpt"],
        pyproject_excerpt=info["pyproject_excerpt"],
        structure=structure_str,
    )


def init_agents_md(cwd: Path, force: bool = False) -> tuple[Path, bool]:
    """生成 AGENTS.md 写到 cwd.

    跟 plan K-8 "additive 0 改" 1:1 配对: 默认 fail-safe (现有 AGENTS.md 0 改).
    除非 force=True 才覆盖.

    Returns:
        (agents_path, created) tuple. created=True 表示新建了 file,
        created=False 表示已存在 (没改) — 跟 caller 1:1 配对.
    """
    agents_path = cwd / "AGENTS.md"
    if agents_path.exists() and not force:
        return agents_path, False  # 0 改 (跟 plan K-8 1:1 配对 additive 0 改)
    agents_path.write_text(render_agents_md(cwd), encoding="utf-8")
    return agents_path, True
